/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Logo/LOGO_2.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function M_LogoObjTwo(props) {
  const { nodes, materials } = useGLTF("/models/Logo/LOGO_2.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve002.geometry}
        material={materials["M1_blue.004"]}
        position={[-0.744, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.45}
      />
      <mesh
        geometry={nodes.Curve013.geometry}
        material={materials["M1_blue.004"]}
        position={[-0.744, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.45}
      />
      <mesh
        geometry={nodes.Curve005.geometry}
        material={materials.LOGO}
        position={[-0.744, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.45}
      />
      <mesh
        geometry={nodes.Curve012.geometry}
        material={materials.LOGO}
        position={[-0.744, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.45}
      />
    </group>
  );
}

useGLTF.preload("../models/Logo/LOGO_2.glb");
