/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/circleBTN/circle_BTN_1.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export const CircleUpPart = React.forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF(
    "../models/circleBTN/circle_BTN_ALL.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        geometry={nodes.Sphere014.geometry}
        material={materials["M1_orange.001"]}
        position={[0, 0.25, 0]}
      />
    </group>
  );
});

useGLTF.preload("../models/circleBTN/circle_BTN_ALL.glb");
