/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/circleBTN/circle_BTN_2.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function CircleBasePart(props) {
  const { nodes, materials } = useGLTF("../models/circleBTN/circle_BTN_2.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials["M1_blue.001"]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials["M1_blue.001"]}
        position={[0, -0.041, 0]}
      />
      <mesh
        geometry={nodes.Sphere006.geometry}
        material={materials.M1_White}
        position={[0, 0.047, 0]}
      />
    </group>
  );
}

useGLTF.preload("../models/circleBTN/circle_BTN_2.glb");
