/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/AllProduct/ALLproduct_base_HighColor.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function M_AllProduct01(props) {
  const { nodes, materials } = useGLTF(
    "/models/AllProduct/ALLproduct_base_HighColor.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials.bake_circle_base}
        position={[-0.631, 0.073, 0.132]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.66}
      >
        <mesh
          geometry={nodes.Sphere001.geometry}
          material={materials.bake_circle_base}
          position={[0, 0.097, 0]}
          scale={[0.828, 0.721, 0.828]}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.bake_triangle_base}
        position={[0.631, 0.073, 0.132]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.66}
      >
        <mesh
          geometry={nodes.Cylinder003.geometry}
          material={materials.bake_triangle_base}
          position={[0, 0.233, 0.181]}
          scale={[1.047, 0.918, 1.047]}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials.bake_square_base}
        position={[-0.631, -1.257, 0.132]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.66}
      >
        <mesh
          geometry={nodes.Cube003.geometry}
          material={materials.bake_square_base}
          position={[0, 0.259, 0]}
          scale={[1.042, 0.802, 1.042]}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials.bake_pentagon_base}
        position={[0.631, -1.257, 0.132]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.66}
      >
        <mesh
          geometry={nodes.Cylinder005.geometry}
          material={materials.bake_pentagon_base}
          position={[0.005, 0.276, 0.067]}
          scale={[1.065, 0.939, 1.065]}
        />
      </mesh>
      <mesh
        geometry={nodes.背板_工作區域_1002.geometry}
        rotation={[Math.PI / 2, 0, 0]}
        material={
          new THREE.MeshStandardMaterial({
            color: 0xffffff,
            emissive: 0xffffff,
            emissiveIntensity: 4,
          })
        }
      />
      <mesh
        geometry={nodes.背板_工作區域_1003.geometry}
        material={materials["背板_工作區域 1.002"]}
        position={[0, 0, 0.029]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/ALLproduct_base_HighColor.glb");
