/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/SingleButton/circleBTN_HighColor.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function M_CircleBTN(props) {
  const { nodes, materials } = useGLTF(
    "../models/SingleButton/circleBTN_HighColor.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.BTN_圓形01002.geometry}
        material={materials.BTN_圓形01}
        position={[-0.627, 0.077, 0.603]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.948}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials.bake_circle_blue}
        position={[-0.631, 0.073, 0.332]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/circleBTN_HighColor.glb");
