/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/SingleButton/pentagonBTN_HighColor.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function M_PentagonBTN(props) {
  const { nodes, materials } = useGLTF(
    "../models/SingleButton/pentagonBTN_HighColor.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.BTN_五角01001.geometry}
        material={materials.BTN_五角01}
        position={[0.649, -1.256, 0.58]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.961}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials.bake_pentagon_blue}
        position={[0.634, -1.302, 0.371]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.634, 0.544, 0.634]}
      />
    </group>
  );
}

useGLTF.preload("/pentagonBTN_HighColor.glb");
