/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/SingleButton/squareBTN_HighColor.glb 
*/

import React, { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";

export const M_SquareBTN = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF(
    "/models/SingleButton/squareBTN_HighColor.glb"
  );
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        geometry={nodes.BTN_方形01001.geometry}
        material={materials.BTN_方形01}
        position={[-0.631, -1.233, 0.581]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials.bake_square_blue}
        position={[-0.631, -1.257, 0.372]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.62, 0.563, 0.62]}
      />
    </group>
  );
});

useGLTF.preload("/squareBTN_HighColor.glb");
