/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/SingleButton/triangleBTN_HighColor.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function M_TriangleBTN(props) {
  const { nodes, materials } = useGLTF(
    "../models/SingleButton/triangleBTN_HighColor.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.BTN_三角01001.geometry}
        material={materials.BTN_三角01}
        position={[0.633, 0.046, 0.598]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.971}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials.bake_triangle_blue}
        position={[0.631, -0.046, 0.389]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.624, 0.543, 0.624]}
      />
    </group>
  );
}

useGLTF.preload("/triangleBTN_HighColor.glb");
